### ISSUE TITLE
Make the login screen fully functional

### ISSUE THREAD

**Issue by chaibytes** [CP-TravelBug/TravelBug#2]
- [x] Add image to the login screen
- [x] Add onClickHandler for TimelineScreen that opens up on clicking login

**Comment by chaibytes** [comment]
Hi Oron this is the screen that I am reaching everytime I try to login through the FB login button from the LoginActivity screen. Can you debug this and let me know if there is anything that I am missing when trying to login.

![screen shot 2016-11-13 at 8 21 16 pm](https://cloud.githubusercontent.com/assets/5689507/20253311/16a4fea2-a9df-11e6-9b63-86bbe9f64473.png)

**Comment by oec08** [comment]
@chaibytes and @arunesh I need your fbid so I can add you as admins for the facebook app, this should fix this error

**Comment by chaibytes** [comment]
Oh cool thanks in advance. Mine is: pragyan.apps@gmail.com

**Comment by oec08** [comment]
@chaibytes that is email address I need the id, what is the id that is trailing in the URL bar, for example mine is https://www.facebook.com/oroncarty. So my id would be **oroncarty**

**Comment by chaibytes** [comment]
https://www.facebook.com/pragyan.apps

Hey Oron can you please try the above. Thanks!

**Comment by oec08** [comment]
Please check now @chaibytes !

**Comment by chaibytes** [comment]
Sorry still seeing the issue. Should I need to do anything else ?

**Comment by chaibytes** [comment]
Btw are u able to login and see the new TimelineActivity with all my new changes ?

**Comment by oec08** [comment]
It says pending for that user, can you delete and reinstall the app

**Comment by oec08** [comment]
@chaibytes can you please verify that this works so I may close this issue?

**Comment by chaibytes** [comment]
yup it works for login !
