### ISSUE TITLE
Update the doc with details of Facebook APIs

### ISSUE THREAD

**Issue by chaibytes** [CP-TravelBug/TravelBug#9]
- Whether FB APIs have friends list exposed that we can use to add users.

**Comment by oec08** [comment]
This can be done, where should I put the documentation for the Facebook API in our project?

**Comment by oec08** [comment]
Here is the link to the documentation
https://github.com/CP-TravelBug/TravelBug/wiki/Using-the-Facebook-API 

I will add more details as I work more with the API

**Comment by chaibytes** [comment]
Good thinking with using the wiki Oron !
